### PR TITLE
Some Needed Fixes

### PR DESCRIPTION
**Pull request by Felli**

### CODE REVIEW

**Comment by WebCrew** [comment]
@Felli - why you edited the theme.css?
And also - why you changed at the login.php the register-form to invite-form? Is it because of the errorException? If YES, does it have no negative effect on the registration now?

**Comment by Felli** [comment]
@WebCrew I pretty much merged #15 within this one, and merged from other [forked repositories](https://github.com/sasha-travkina/humhub-themes-flathub/network/members), all in all things are working for me very well! :)

**Comment by WebCrew** [comment]
@Felli I also did some edits like You did within my theme and I also have no problems so far, so it seems that all is working well as it should. The only thing which I not did is to edit the css files because the css files are main parts of the FlatHub theme or in my case of my Theme.

**Review by Felli — COMMENTED** [review]
This should fix the issues of #14

**Comment by WebCrew** [comment]
Why not setup Your name at the README file by Autors? You helped to update the theme, so You should be named :)

I hope Alexandra will come back some day to merge the pull requests.

**Comment by Felli** [comment]
You'll see [here](https://github.com/Felli/humhub-themes-flathub/blob/master/README.md#edited-by) that I have added credit to myself for helping out with the theme. :+1: .

**Review by WebCrew — COMMENTED** [review]
Why you have to change the:

.layout-sidebar-container #share-panel {
		display: none;		
}

For my opinion it can become a issue with the responsive view at Tablet PC`s. Because the 

.layout-sidebar-container #share-panel {
display: none;		
}

depends to  @media (max-width:991px) and thats for Tablet PC`s and the responsive view.

**Comment by Felli** [comment]
That was originally in the theme.css I accidentally removed it when adding scrollme.js into the theme, tho I might have broken it slightly as my test site kinda broke after a refresh with the 1.2 version. :laughing:

**Review by WebCrew — APPROVED** [review]
Thumbs up, well done!

**Comment by WebCrew** [comment]
Hi @Felli would you be so kind and create a very own repository with the FlatHub Theme and your changes, because I think @sasha-travkina will never come back to combine your branches with her master branch?

**Pull request closed without merging**
